version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - redash-network

volumes:
  postgres_data:


networks:
  redash-network:
    name: redash-network
